FROM python:3.7-alpine
RUN apk add --no-cache gcc musl-dev linux-headers
WORKDIR /app
COPY app.py requirements.txt /app
RUN pip install --no-cache install -r requirements.txt
EXPOSE 9000
CMD ["python3", "app.py"]